### PR TITLE
Update GEFS tag from global-workflow and fix directory 

### LINKED ISSUE #132: Update checkout.sh and link_gefs.sh to accomodate bugfix and new fix directory
The current `checkout.sh` and `link_gefs.sh` scripts are outdated and need to be updated:

- [x] Update global-workflow tag from "gefs_v12.3.6" to "gefs_v12.3.8" in `checkout.sh`.
- [x] Update fix directory in `link_gefs.sh` to point to the gfs fix directory with new CO2 files (Ref [#1924](https://github.com/NOAA-EMC/global-workflow/issues/1924)).

### PR DESCRIPTION
**Pull request by EricSinsky-NOAA**
This draft PR intends to update the GEFS tag in global-workflow from v12.3.6. to v12.3.8. This new tag includes a bugfix in gsl-prep-chem (more details on this bugfix can be found in gsl-prep-chem [issue #9](https://github.com/NOAA-GSL/GSL-prep-chem/issues/9)). Furthermore, `FIX_DIR_FV3` in `.sorc/link_gefs.sh` is updated to a directory that contains the most recent CO2 files. This draft PR addresses GEFS issue #132. When the location of the new fix directory is confirmed, this draft PR will change into a normal PR. This draft PR should not be merged until the new fix directory is confirmed. When this PR is merged, it will resolve GEFS issue #132.

### CODE REVIEW

File: sorc/link_gefs.sh [hunk 1]
```diff
@@ -30,10 +30,10 @@ pwd=$(pwd -P)
 #------------------------------
 if [ $machine = "hera" ]; then
     FIX_DIR="/scratch2/NCEPDEV/ensemble/noscrub/common/FIX/gefs/fix_nco_gefsv12.3"
-    FIX_DIR_FV3="/scratch1/NCEPDEV/global/glopara/fix"
+    FIX_DIR_FV3="/scratch1/NCEPDEV/global/glopara/fix_nco_gfsv16.3.0"
 elif [ $machine == "wcoss2" ]; then
     FIX_DIR="/lfs/h2/emc/ens/save/emc.ens/FIX/gefs/fix_nco_gefsv12.3"
-    FIX_DIR_FV3="/lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv15"
+    FIX_DIR_FV3="/lfs/h2/emc/global/save/emc.global/FIX/fix_nco_gfsv16.3.0"
```
Comment (EricSinsky-NOAA) [inline sorc/link_gefs.sh]: @WalterKolczynski-NOAA Can you confirm that these are the correct and most recent fix directories for Hera and WCOSS2 with the new CO2 files?

Comment (WalterKolczynski-NOAA) [reply sorc/link_gefs.sh]: Yes (for ops), but you should not be moving to them. There are going to be a lot more fix changes than just the CO2 and the v16 files may not be compatible with the v15-based GEFS. I will add the new CO2 files to the v15 directory.

CC: @KateFriedman-NOAA

Comment (EricSinsky-NOAA) [reply sorc/link_gefs.sh]: @WalterKolczynski-NOAA Thanks for adding the new CO2 fix files to the v15 directory. The goal is to match the data that NCO has now in `/lfs/h1/ops/prod/packages/gefs.v12.3.8/fix/` for operational GEFSv12.

Comment (WalterKolczynski-NOAA) [reply sorc/link_gefs.sh]: Kate actually did the copying, but it should be everywhere except Orion now (we don't seem to have v15 on Orion).

Comment (KateFriedman-NOAA) [reply sorc/link_gefs.sh]: The new CO2 files have been added to the `fix_nco_gfsv15` sets on supported platforms.

Comment (EricSinsky-NOAA) [reply sorc/link_gefs.sh]: Thank you @KateFriedman-NOAA for adding the new CO2 files to the v15 directory on Hera and WCOSS2. I will make no changes to the `FIX_DIR_FV3` variable.

**Comment by EricSinsky-NOAA** [comment]
The location of the GFS fix directories have been confirmed. This draft PR is ready for review.

**Review by WalterKolczynski-NOAA — APPROVED** [review]
